// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type UserInfo struct {
	UserID   uint   `json:"userId"`
	Avatar   string `json:"avatar"`
	Nickname string `json:"nickname"`
}

type GroupCreateRequest struct {
	Token      string `header:"Authorization"`
	Mode       int8   `json:"mode,optional"` // 模式  1 直接创建模式 2 选人创建模式
	Name       string `json:"name,optional"`
	IsSearch   bool   `json:"isSearch,optional"`   // 是否可以搜到
	Size       int    `json:"size,optional"`       // 群规模
	UserIDList []uint `json:"userIdList,optional"` // 用户id列表
}

type GroupCreateResponse struct {
}

type GroupInfoRequest struct {
	Token string `header:"Authorization"`
	ID    uint   `path:"id"` //群id
}

type GroupInfoResponse struct {
	GroupID           uint       `json:"groupId"`
	Title             string     `json:"title"`
	Abstract          string     `json:"abstract"`
	MemberCount       int        `json:"memberCount"`
	MemberOnlineCount int        `json:"memberOnlineCount"`
	Avatar            string     `json:"avatar"`
	Creator           UserInfo   `json:"creator"`
	AdminList         []UserInfo `json:"adminList"`
}
