// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type ChatHistoryRequest struct {
	Page  int `form:"page"`
	Limit int `form:"limit"`
}

type ChatHistoryResponse struct {
	ID        uint   `json:"id"`
	UserID    uint   `json:"userId"`
	Avatar    string `json:"avatar"`
	Nickname  string `json:"nickname"`
	CreatedAt string `json:"created_at"` // 消息时间
}
