// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginInfo struct {
	Token string `json:"token"`
}

type LoginRequest struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Code int       `json:"code"`
	Data LoginInfo `json:"data"` //相应一个LoginInfo对象，里面又Token属性
	Msg  string    `json:"msg"`
}

type OpenLoginInfo struct {
	Name string `json:"name"` //用户名
	Icon string `json:"icon"` //用户头像
	Href string `json:"href"` // 跳转地址
}

type OpenLoginInfoResponse struct {
	Code int             `json:"code"`
	Data []OpenLoginInfo `json:"data"`
	Msg  string          `json:"msg"`
}

type RegisterInfo struct {
	UserName string `json:"username"`
}

type RegisterRequest struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	Code int          `json:"code"`
	Data RegisterInfo `json:"data"`
	Msg  string       `json:"msg"`
}

type Response struct {
	Code int    `json:"code"`
	Data string `json:"data"`
	Msg  string `json:"msg"`
}
